<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.11.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" />
  </ItemGroup>

  <PropertyGroup>
    <PackageId>MBSD.Analysers.RedundantCode</PackageId>
    <Version>1.0.9</Version>
    <Authors>Matt Bohan</Authors>
    <Description>Analyzes code for redundancy across the entire solution.</Description>
    <PackageTags>analyzer;roslyn;redundant;code</PackageTags>
    <RepositoryUrl>https://github.com/matt-bohan/redundant-code-analyser</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/matt-bohan/redundant-code-analyser</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="" />
  </ItemGroup>
	<ItemGroup>
		<Analyzer Include="$(TargetPath)" Pack="true" PackagePath="analyzers/dotnet/cs" />
	</ItemGroup>

</Project>

